# Generated by Django 5.1.4 on 2025-01-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_usuario_contraseña_remove_usuario_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeseos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imagen_url', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
